### ISSUE TITLE
Error in connection [BUG]

### ISSUE THREAD

**Issue by SURAJPATIL6088** [lakshya-20/supply-chain#26]
**Describe the bug**

Area Where Bug Occurred

- [ ] UI/UX
- [ ] Business Logic

**How to reproduce the error/bug**
1. run the project
2. after connecting the metamask account

**Before submitting an issue check the below**

- [ ] I have synced all my node versions as mentioned in the project"
- [ ] I am using the same version of npm as is the project
- [ ] My current branch is in sync with the development branch

when i run the project i get these page but the profile page is not opening as well as i don't have any option like addng product and farmers.
![image](https://github.com/lakshya-20/supply-chain/assets/78692972/c967ad11-263a-46a9-b0b7-636811d93299)

**Comment by lakshya-20** [comment]
Hello @SURAJPATIL6088 
The first thing to check is that you are logged in with the account you used to deploy smart contracts on Ganache, which would be the admin account for the application. If already there try redeploying the contracts.

To get a farmer in the application, you have to log in with a different account and register as a farmer.
To add products, you be logged in with a manufacturer account that you can get by registering a new account as a manufacturer.
